language: objective-c
osx_image: xcode10.2

install:
  - gem install xcpretty
  - sudo gem install cocoapods -v 1.6.1
  - pod setup
  - pod install

script:
- pod lib lint
- xcodebuild clean build test -workspace SwiftPromises.xcworkspace -scheme SwiftPromises_Tests -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' -sdk iphonesimulator12.2 CODE_SIGNING_REQUIRED=NO -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES -enableCodeCoverage YES | xcpretty -c
- bash <(curl -s https://codecov.io/bash) -cF unit -J SwiftPromises
